version: "3"
services:
  app:
    container_name: overseer
    # image: overseer
    build: .
    restart: always
    command: bundle exec ruby ./app.rb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Another volume for ontrack FS

# TODO: Maybe add inheritence.. https://docs.docker.com/compose/reference/overview/#specifying-multiple-compose-files
# Solution: Use different dockerfiles, probably one that uses multi-stage build https://docs.docker.com/develop/develop-images/multistage-build/

