version: "3"
services:
  overseer-app:
    container_name: overseer
    build: .
    command: bundle exec ruby ./app.rb
    env_file:
      - overseer.env
    volumes:
      # App's code path - not required in final image
      - .:/app

      # Host path for writing the output of execution - required.
      # TODO: Test by mounting an actual XFS volume.
      - ../data/overseer-instances/1:/home/overseer/work-dir
      # Path for reading OnTrack files from - required.
      # TODO: Map this directly to a constant path that can be written to,
      # as the path will be a part of the messages
      # received from OnTrack via RabbitMQ.
      # TODO: Make the path rw by overseer in docker image.
      - ../data/student-work:/student-work
