version: "3"
services:
  app:
    container_name: overseer
    # image: overseer
    build:
      context: .
      dockerfile: ./development.Dockerfile
    command: bundle exec ruby ./app.rb
    volumes:
      # App's code path - not required in final image
      - ./:/app
      # Docker socket path - required.
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
      # Host path for writing the output of execution - required.
      # TODO: Test by mounting an actual XFS volume.
      - ${HOST_XFS_VOLUME}:/home/overseer/work-dir
      # Path for reading OnTrack files from - required.
      # TODO: Map this directly to a constant path that can be written to,
      # as the path will be a part of the messages
      # received from OnTrack via RabbitMQ.
      # TODO: Make the path rw by overseer in docker image.
      - ${ONTRACK_VOLUME}:${DOCKER_ONTRACK_VOLUME}
