version: "3"
services:
  app:
    container_name: overseer
    build: .
    restart: always
    command: ./app.rb

# TODO: Maybe add inheritence.. https://docs.docker.com/compose/reference/overview/#specifying-multiple-compose-files
# Solution: Use different dockerfiles, probably one that uses multi-stage build https://docs.docker.com/develop/develop-images/multistage-build/

