version: "3"
services:
  app:
    container_name: overseer
    # image: overseer
    build:
      context: .
      dockerfile: ./development.Dockerfile
    command: bundle exec ruby ./app.rb
    volumes:
      - ./:/home/overseer/app
      - /var/run/docker.sock:/var/run/docker.sock
      # Another volume for ontrack FS
