version: "3"
services:
  app:
    container_name: overseer
    command: bundle exec ruby ./app.rb
    volumes:
      # Docker socket path - required.
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
      # Host path for writing the output of execution - required.
      - ${HOST_XFS_VOLUME}:/work-dir
      # Path for reading OnTrack files from - required.
      # Is maped directly to itself as the path will be a part of the messages
      # received from OnTrack via RabbitMQ.
      - ${ONTRACK_VOLUME}:${ONTRACK_VOLUME}
