name: create-doubtfire-overseer
on:
  push:
    tags:
      - 'v*'
    branches:
      - '*.x'
      - 'development'
      - 'main'
  deployment:
  workflow_dispatch:
jobs:
  docker-overseer:
    if: github.repository_owner == 'doubtfire-lms'
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for Overseer
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: lmsdoubtfire/overseer
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern=prod-{{version}}
            type=semver,pattern=prod-{{major}}.{{minor}}
            type=semver,pattern=prod-{{major}}
      - name: Build and push overseer
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
